# Generated by Django 3.2 on 2021-10-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('allowed_specialities', models.ManyToManyField(related_name='allowed_subjects', to='groups.Speciality', verbose_name='Специальности, которым доступна данная дисциплина')),
            ],
            options={
                'verbose_name': 'Предмет (учебная дисциплина)',
                'verbose_name_plural': 'Предметы (учебные дисциплины)',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='subjects.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='lectures/', verbose_name='Файл(лекция)')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='subjects.semester', verbose_name='Семестр')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='labs/', verbose_name='Файл(лаба)')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='subjects.semester', verbose_name='Семестр')),
            ],
            options={
                'verbose_name': 'Лабораторная работа',
                'verbose_name_plural': 'Лабораторные работы',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='subjects.semester', verbose_name='Семестр')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='additional_files/', verbose_name='Файл')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='subjects.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
