# Generated by Django 3.2 on 2021-10-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название устройства')),
                ('host', models.CharField(max_length=50, verbose_name='Хост')),
                ('port', models.CharField(default='', max_length=20, unique=True, verbose_name='Порт')),
                ('username', models.CharField(default='', max_length=150, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='MainCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=150, unique=True, verbose_name='Команда')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Subcommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcommand_name', models.CharField(max_length=150, verbose_name='Подкоманда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcommands', to='console.maincommands', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подкоманда',
                'verbose_name_plural': 'Подкоманды',
            },
        ),
    ]
