# Generated by Django 3.2 on 2021-10-24 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
        ('simple_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='testsresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simple_tests.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='test',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='subjects.lab', verbose_name='Лабораторная работа'),
        ),
        migrations.AddField(
            model_name='test',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='subjects.lecture', verbose_name='Лекция'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='simple_tests.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answerresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_results', to='simple_tests.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='answerresult',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='simple_tests.testsresult', verbose_name='Результат теста'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='simple_tests.question', verbose_name='Вопрос'),
        ),
        migrations.AlterUniqueTogether(
            name='answeroption',
            unique_together={('answer', 'question')},
        ),
    ]
