# Generated by Django 3.2 on 2024-03-16 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_gns3',
            field=models.BooleanField(default=False, verbose_name='Выполнять в GNS?'),
        ),
        migrations.AlterField(
            model_name='testsresult',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 15, 4, 35, 399524), verbose_name='Дата завершения'),
        ),
    ]
